### ISSUE TITLE
Use the Java 8 Date/Time api

### ISSUE THREAD

**Issue by Tostino** [fdreyfs/vaadin-tuning-datefield#11]
It would be very nice to be able to use the new Date/Time API provided in Java 8 (either in addition to, or instead of JodaTime).

**Comment by igorbljahhin** [comment]
+1

**Comment by SynkovAndrew** [comment]
+1

**Comment by fdreyfs** [comment]
Hi,

With the upcoming Vaadin8 version of the plugin I will switch to java.time API.
Please give me your email address so that I can send you a prepared version of the Vaadin8+java.time plugin.
If it's alright with you I will upload it.

Regards,

Fred

**Comment by igorbljahhin** [comment]
Hi, Fred! It is same email address as you #18 : igor.bljahhin@gmail.com

**Comment by fdreyfs** [comment]
Hey Igor, yes the comment was for the other ones :)
You can use the same link as sent you before, I uploaded the jars with Vaadin8+java.time API version (the non-joda jars)

**Comment by igorbljahhin** [comment]
@SynkovAndrew is my teammate :)

**Comment by fdreyfs** [comment]
Lol, ok then :) The jars are available

**Comment by igorbljahhin** [comment]
Thank you, we are looking at them already.

**Comment by igorbljahhin** [comment]
Java Time version is working OK!

**Comment by fdreyfs** [comment]
I uploaded the vaadin8 + java.time on the repo
Regards
Fred
