### ISSUE TITLE
Year selector doesn't work.

### ISSUE THREAD

**Issue by j1u4hoctb** [fdreyfs/vaadin-tuning-datefield#12]
Selector probably misses click listener :)

Checked on both 0.14.0 and 0.15.0 versions.

**Comment by fdreyfs** [comment]
Hi,
Could you be more specific please? I don't see where there is a pb :)
Could you provide a use case?

Thanks

Fred

**Comment by j1u4hoctb** [comment]
I'm not able to select year. By this I mean quick year selection.
I can select date, I can select month, but not year :(

Does It help? :)

**Comment by fdreyfs** [comment]
Sorry, it does not...What do you mean by "I can't select a year" ?
Are you talking about a YearChangeListener listener which is not fired ?

Please tell me more about the use case. 
Ex: the calendar is open, I click on the month button on the top of the calendar, then on the next month button, etc.... When I click on X I expect this...but here is what happen"

Cheers,

Fred

**Comment by j1u4hoctb** [comment]
​​Problem solved.

​With custom implementation of CellItemCustomizer there are two methods
isEnabled(...). By default they return false value,
I've changed first to true, but missed the second one.   ​

**Comment by fdreyfs** [comment]
Alright,
let me know if you think the documentation is missing something so that you could have solved this issue faster.
Regards,

Fred
