### ISSUE TITLE
Vaadin 8 ?

### ISSUE THREAD

**Issue by eliasmav** [fdreyfs/vaadin-tuning-datefield#18]
I am using your useful and very nice Addon, any plans to transfer also to Vaadin 8.
Regards
Elias

**Comment by fdreyfs** [comment]
Hi Elias,
Thank you for your email.
Actually I started the conversion a few weeks ago, but had to switch to urgent matters and did not have the time to test everything on it.
I can provide an working beta version right now as a jar if you want, so you can tell me if it suits your needs.
If you tell me it's working as is I will upload it (as beta) to the repository.

Regards,
Fred

**Comment by eliasmav** [comment]
Good afternoon Fred,
Thanks you for reply. I am so sorry for my late reply but the previous week i was changing house so everything was a big mess.
With glad I will check if the jar is "ok" with the functionality that i am using.
RegardsElias
 
 

    On Wednesday, June 7, 2017 11:59 AM, fdreyfs <notifications@github.com> wrote:
 

 Hi Elias,
Thank you for your email.
Actually I started the conversion a few weeks ago, but had to switch to urgent matters and did not have the time to test everything on it.
I can provide an working beta version right now as a jar if you want, so you can tell me if it suits your needs.
If you tell me it's working as is I will upload it (as beta) to the repository.Regards,
Fred—

**Comment by igorbljahhin** [comment]
Hello, Fred!
I am also interested in the version for Vaadin 8. Could you please share it with me too?

**Comment by fdreyfs** [comment]
Hi Igor,
Please send me your email address so that I can share the jars to you.
Regards,
Fred

**Comment by igorbljahhin** [comment]
It's igor.bljahhin@gmail.com. Thanks in advance!

**Comment by igorbljahhin** [comment]
Thank you, I got it.

**Comment by fdreyfs** [comment]
I'm planning of releasing the vaadin8 version of the plugin with use of Java8 time API instead of Joda. You will be able to wrap a CustomField around the java.time version of it if you use Joda in your project.
What do you think ?

**Comment by igorbljahhin** [comment]
Sounds good for me. We are using Java Time API in our project.

**Comment by igorbljahhin** [comment]
We took this version and we have no issues with it. Thank you very much!

**Comment by fdreyfs** [comment]
I uploaded the vaadin8 + java.time on the repo
Regards
Fred
