### ISSUE TITLE
NullPointerException in removeDateRange

### ISSUE THREAD

**Issue by ohens** [fdreyfs/vaadin-tuning-datefield#20]
Hello!

I just tried using your addon with Vaadin 8.1. Thanks by the way for this useful addon!

Unfortunately, I get a NPE when using range validators.

I guess, it's coming from this method (lines 499-503):

```
public void removeDateRange() {
        if (dateRangeValidator != null) {
            dateRangeValidator = new RangeValidator<LocalDate>(null, Comparator.naturalOrder(), null, null);
        }
    }
```

Looks like RangeValidator does not accept 'null' as message.

Regards Onno

**Comment by fdreyfs** [comment]
Hi,
Thank you for spotting this bug.
Indeed the null message is forbidden.
I'm uploading a 0.20.0-vaadin8 version of the plugin right away

**Comment by fdreyfs** [comment]
New version uploaded, thank you very much !
Please take a few seconds to rate the addon if you haven't done it before.
Regards
Fred

**Comment by ohens** [comment]
Wow, thanks a lot for this quick bugfixing and release. I already wanted to clone your repo to be able to continue working, but this way is much better!
