### ISSUE TITLE
The setDateTextReadOnly don't works.

### ISSUE THREAD

**Issue by ambrits** [fdreyfs/vaadin-tuning-datefield#6]
Hi!
Please help me a little bit.
I was very happy when I found your add-on. I installed it, added the project dependency (ivy), inherited the module in gwt.xml file and recompiled the widgets. I set the setDateTextReadOnly(true), but it doesn’t works, I can write into the datetext. What did I wrong?

Thanks,
Best regards
Tamás

**Comment by fdreyfs** [comment]
Hi,

Thank you for your feedback.
You did nothing wrong, it's a bug.
I fixed it and released version 0.12.0

Please take time to rate this addon if you like it. The more it's rated,
the more it's used, the more I get feedbacks and the better I can fix
issues ;)

Best regards,

Fred


2015-02-24 15:07 GMT+01:00 ambrits <notifications@github.com>:

**Comment by ambrits** [comment]
Hi!

Thanks You! It's working fine! :)
I have already rated it.

Best regards
Tamás

**Comment by fdreyfs** [comment]
Thank you very much !

Best regards,

Fred

2015-02-24 16:39 GMT+01:00 ambrits <notifications@github.com>:
