### ISSUE TITLE
Two month at once?

### ISSUE THREAD

**Issue by tobit800** [fdreyfs/vaadin-tuning-datefield#7]
Hello,
Thank You very much for this great addon.

I would like to add a new TwoMonthCalendarTable, which shows two following month.
How should I do that?
Could I extend AbstractCalendarTable like  DayCalendarTable, but with numberOfColumns=14
and an extended renderHeader() ?

Tobias

**Comment by fdreyfs** [comment]
Hi Tobias,
Thanks for using my addon, I hope it's useful to you.

Concerning you request, could you describe in which context/use case you would want to display 2 months instead of one (and use the fast controls to switch months) ?
For now I don't know if extending AbstractCalendarTable may or may not be the right solution, it will depend on the story you'll tell me :) . 

Regards,

Fred

**Comment by tobit800** [comment]
Hi Fred,

I´ll try to tell you the story:

The customer of our website is a patient, which can book an doctor´s appointment. 
We show in the two-month-calendar the free time (blocks of 15 Minutes) from the doctor for the next six to ten weeks. 
The website should show the next two month. The button "Next month" is only enabled, when the doctor has send us blocks after the end of the next month.
The "Previous month"-button must not go past the first block.
The first block is after today -> No appintment on the same day, but ppointment for tommorow are OK.

The idea of the two month calendar is, that the patient can see more than the days from the rest of the actual month. Because on January 31 we would only show free blocks for the next 5 days.

I don´t want to use two calendar widgets, because the patient should only select one day. With two caldendar widgets, we have two selected days. I would have to de-select the first calendar when the patient selects a day in the second calendar widget.

It seems easier for me to extend your calendar to show two month, than to handle the de-select-events.

Thanks a lot. Best regards 
Tobias

**Comment by fdreyfs** [comment]
Hi Tobias,

Thank you for your story.
Are you willing to use the calendar inline mode (which is I believe according to your story) or the datefield mode ?
If you want to use the inline mode the best way would be to create a CustomField which holds 2 InlineTuningDateField and handle the de-select. For this I can give you some inlights.
If you want to use the datefield mode, then it won't be a piece of cake, but it's feasible.

Cheers,

Fred

**Comment by tobit800** [comment]
Hi Fred

I want to use the inline mode. For now i have 
![screenshot_072_mozilla firefox](https://cloud.githubusercontent.com/assets/6237869/6801431/dfa24706-d227-11e4-8df4-d7f421a0e975.png)

I use two InlineTuningDateField kalenderLinks und kalenderRechts (left and right in german):
https://gist.github.com/tobit800/e925c01ec68bf0cbf31e

I think with the little boolean flag 'changing', i solved the problem of endles feedback when one component changes the other and vice versa.

Now I am working on the following problem:
I have to disable the previous month button, when it would bring the left calender into past.
I have to disable the next month button, when it would bring the right calender past the last block.

I am very thankfull for every help and can´t wait to hear what you can tell me to my code.
Tobias

**Comment by fdreyfs** [comment]
Tobias,
I'm not sure relying on controls may solve your problem.
What I suggest is to disable controls on right calendar and have only controls on left one : 

![capture d ecran 2015-03-24 a 17 40 24](https://cloud.githubusercontent.com/assets/4209730/6807131/f4ff8760-d24c-11e4-96c0-f24c1b3c615c.png)

It would be much easier for the end-user to control a "master" calendar and see its next-month slave calendar (you could even style the current month calendar differently from next month calendar).
What do you think about this?

There is a small bug in your code when you click on the calendar resolution button (the month button) and change month.
The other calendar does not update.

Fred

**Comment by tobit800** [comment]
Hi Fred!

Thanks a lot for your answer.
I haven´t realized the but in my code, but you are right.

For now I have disabled the controls on both sides and add two new buttons (prev and next).
This is not so elegant, but I have better control over the buttons. So the button are only enabled in a valid time range. I.e. prev-button disabled, when the left calendar shows the current month. etc.

![screenshot_074_mozilla firefox](https://cloud.githubusercontent.com/assets/6237869/6808366/da7d7c7e-d253-11e4-893a-8536353569a7.png)

As you can see, I have changed the colors to fit into the rest of my app. With your css this is also easy. 

It was really kind of you to help me. Best regards,
Tobias

**Comment by fdreyfs** [comment]
Hi,

I'm glad you figured a way out. This solution (delegating to external buttons) is not that bad in your use case.

If you haven't done it before, please take a minute to rate the plugin.

Thank you!
Regards,
Fred
