### ISSUE TITLE
Locale settings don't change date grid layout

### ISSUE THREAD

**Issue by j1u4hoctb** [fdreyfs/vaadin-tuning-datefield#9]
In your demo, there is a field called "French TuningDateField with pattern dd/MM/yyyy" with France locale.
And. Both weekend days are at the end of the week.
But from my side with France locale these days (Sunday and Saturday) are at the beginning and end of the week (like all other examples in your demo). I've checked a lot of locales - still the same.

My code snippet is very simple:

public class SmallCalendar extends InlineTuningDateField {
    public SmallCalendar(){
        super();
        setLocale(Locale.FRANCE);
    }
}

**Comment by fdreyfs** [comment]
Hi Oleg,

Thank you for spotting this issue.
It's a small bug that avoid resetting the first/last day of week when changing the locale.
In your case the default locale sets the first/last days to beginning and end and these are not changed when you switch the locale.

I will fix that.

As a short-time workaround you can override the first/last day of week using setFirstDayOfWeek() and setLastDayOfWeek() methods after setting your locale.

**Comment by j1u4hoctb** [comment]
Cool, thank you a lot.

**Comment by fdreyfs** [comment]
Oleg,

This has been fixed in version 0.14.0 which is now available.
Thank you for spotting this bug. Let me know if everything is OK.

Cheers,

Fred

**Comment by j1u4hoctb** [comment]
WHOA! It works, thank you!
